#!/bin/bash
#PBS -l select=1:ncpus=1:mpiprocs=0:nmics=0:mem=100Gb
#PBS -l walltime=12:00:0
#PBS -l cput=10:0:0   
#PBS -j oe
#PBS -m ae
#PBS -M ryoung@unlv.edu
#PBS -V
#PBS -N ric-picard-stage4

# uses /dev/shm for TMP_DIR (good for < 64Gb of temp space)

declare -a fileName=( 

'HG00178.mapped.ILLUMINA.bwa.FIN.exome.20121211.bam',
'HG00190.mapped.ILLUMINA.bwa.FIN.exome.20120522.bam',
'HG00267.mapped.ILLUMINA.bwa.FIN.exome.20130415.bam',
'HG00663.mapped.ILLUMINA.bwa.CHS.exome.20120522.bam',
'HG01111.mapped.ILLUMINA.bwa.PUR.exome.20120522.bam'


 );

for FILEVAR in ${fileName[@]}

do
    # get name of the file being read
    prefix=${FILEVAR:0:7}

nipm=/storage/nipm
tmpdir=/dev/shm/ric
input=${nipm}/1KG-RIC/RAW/$FILEVAR

echo "-----------------------------------------------------"
echo "working on $FILEVAR "
echo "prefix = $prefix"
echo "filevar = ${nipm}/1KG-RIC/RAW/$FILEVAR"
echo "Tempdir = ${tmpdir}"
echo "All the Raw Bam files are here: ${nipm}/1KG-RIC/RAW/ "
echo "Today is $(date)"
echo "-----------------------------------------------------"


sortedOutput=${nipm}/ric/bam-vcf-pipeline/done/sorted-$prefix.bam
markedOutput=${nipm}/ric/bam-vcf-pipeline/done/marked-$prefix.bam
groupedOutput=${nipm}/ric/bam-vcf-pipeline/done/group-$prefix.bam
indexedOutput=${nipm}/ric/bam-vcf-pipeline/done/group-$prefix.bai
vcf=${nipm}/ric/bam-vcf-pipeline/done/$prefix.vcf

echo "-----------------------------------------------------"
echo "first file = ${nipm}/1KG-RIC/RAW/$FILEVAR "
echo "sorted output = ${nipm}/ric/bam-vcf-pipeline/done/sorted-$prefix.bam"
echo "marked output = ${nipm}/ric/bam-vcf-pipeline/done/marked-$prefix.bam"
echo "grouped output = ${nipm}/ric/bam-vcf-pipeline/done/group-$prefix.bam"
echo "index output = ${nipm}/ric/bam-vcf-pipeline/done/indexed-$prefix.bai"
echo "vcf=${nipm}/ric/bam-vcf-pipeline/done/$prefix.vcf"
echo "-----------------------------------------------------"

export JAVA_HOME=/home/ric/jdk1.8.0_72
export PATH=${JAVA_HOME}/bin:${PATH}

echo "-----------------------------------------------------"
echo "Sorting"
echo "-----------------------------------------------------"

if [ -f ${sortedOutput} ] ; then
  echo Aborting sorted output already exists 
  echo ${sortedOutput}
  exit -1
fi

java -Xmx4g  -jar /storage/nipm/APPS/picard/dist/picard.jar SortSam \
       TMP_DIR=${tmpdir} \
       INPUT=${input}  \
       OUTPUT=${sortedOutput} \
       SORT_ORDER=coordinate \
       VALIDATION_STRINGENCY=LENIENT

echo "-----------------------------------------------------"
echo "sorting done"
echo "-----------------------------------------------------"

echo "-----------------------------------------------------"
echo "Marking duplicates"
echo "-----------------------------------------------------"

java -Xmx4g -jar /storage/nipm/APPS/picard/dist/picard.jar MarkDuplicates \
	TMP_DIR=${tmpdir} \
	INPUT=${sortedOutput}  \
	OUTPUT=${markedOutput} \
	METRICS_FILE=metrics.txt VALIDATION_STRINGENCY=LENIENT
echo "-----------------------------------------------------"
echo "Marking Dupes Done"
echo "-----------------------------------------------------"

echo "-----------------------------------------------------"
echo "Add Or Replace Groups"
echo "-----------------------------------------------------"

java -Xmx4g -jar /storage/nipm/APPS/picard/dist/picard.jar  AddOrReplaceReadGroups \
  TMP_DIR=${tmpdir} \
  INPUT=${markedOutput}  \
  OUTPUT=${groupedOutput} \
  RGID=group1 \
  RGLB=lib1 \
  RGPL=illumina \
  RGPU=unit1 \
  RGSM=$prefix \
  VALIDATION_STRINGENCY=LENIENT

echo "-----------------------------------------------------"
echo "replacing groups done"
echo "-----------------------------------------------------"

echo "-----------------------------------------------------"
echo "Build Bam Index $FILEVAR"
echo "-----------------------------------------------------"

   java -Xmx4g -jar /storage/nipm/APPS/picard/dist/picard.jar BuildBamIndex \
    TMP_DIR=${tmpdir} \
    INPUT=${groupedOutput} \
    OUTPUT=${indexedOutput} \
    VALIDATION_STRINGENCY=LENIENT
echo "-----------------------------------------------------"
echo "done building index "
echo "-----------------------------------------------------"


echo "-----------------------------------------------------"
echo "FUN TIME  Variant Discovery $FILEVAR"
echo "-----------------------------------------------------"

  /usr/bin/time java -Xmx10g \
                -Djava.io.tmpdir=${tmpdir} \
                -jar /storage/nipm/APPS/GATK/GenomeAnalysisTK.jar \
                -T UnifiedGenotyper \
                -R /storage/nipm/REFERENCES/g1k-human_v37/human_g1k_v37.fasta \
                -nct 4 -nt 8 \
                -I ${groupedOutput} \
                -o ${vcf}

echo "-----------------------------------------------------"
echo "VCF Gen done"
echo "-----------------------------------------------------"

echo "-----------------------------------------------------"
echo "Spring Cleaning"
echo "-----------------------------------------------------"


rm -rf ${tmpdir}
done
echo "-----------------------------------------------------"
echo "done"
echo "-----------------------------------------------------"