#!/bin/bash
#PBS -l select=1:ncpus=1:mpiprocs=0:nmics=0:mem=100Gb
#PBS -l walltime=12:00:0
#PBS -l cput=10:0:0   
#PBS -j oe
#PBS -m ae
#PBS -M ryoung@unlv.edu
#PBS -V
#PBS -N test-bam-100g

# uses /dev/shm for TMP_DIR (good for < 64Gb of temp space)

nipm=/storage/nipm
tmpdir=/dev/shm/ric
input=${nipm}/1KG-RIC/RAW/HG01973.mapped.ILLUMINA.bwa.PEL.exome.20120522.bam
sortedOutput=${nipm}/ric/bam-vcf-pipeline/done/sorted-1973.bam
markedOutput=${nipm}/ric/bam-vcf-pipeline/done/marked-1973.bam


export JAVA_HOME=/home/ric/jdk1.8.0_72
export PATH=${JAVA_HOME}/bin:${PATH}

echo "Sorting"

if [ -f ${sortedOutput} ] ; then
  echo Aborting sorted output already exists 
  echo ${sortedOutput}
  exit -1
fi

java -Xmx4g  -jar /storage/nipm/APPS/picard/dist/picard.jar SortSam \
       TMP_DIR=${tmpdir} \
       INPUT=${input}  \
       OUTPUT=${sortedOutput} \
       SORT_ORDER=coordinate \
       VALIDATION_STRINGENCY=LENIENT

echo "Marking duplicates"
java -Xmx4g -jar /storage/nipm/APPS/picard/dist/picard.jar MarkDuplicates \
	TMP_DIR=${tmpdir} \
	INPUT=${sortedOutput}  \
	OUTPUT=${markedOutput} \
	METRICS_FILE=metrics.txt VALIDATION_STRINGENCY=LENIENT

rm -rf ${tmpdir}
echo "done"